version: '3'
services:
  database:
    image: 'postgres'
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./pg-db/:/var/lib/postgresql/data/
  redis:
    image: 'redis'
    ports:
      - 6379:6379
